<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/2_Advanced/05_Pandas_Index_Management.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Pandas Index Management

Load data.

In [ ]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## Index Attributes

### Notes

* You can get or set properties of the index, such as its name or data type.  
* It's helpful for maintaining metadata or ensuring index compatibility in operations.
* `(index.name, index.dtype)`
    * `index.name` - name of the index
    * `index.dtype` - data type of the index

Let's look at our DataFrame.

In [2]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
384287,Data Analyst,Data Analyst/Project Support - Immediate Start,"Glasgow, UK",via Your Basin Jobs,None,False,United Kingdom,2023-04-24 18:20:05,True,False,United Kingdom,None,NaN,NaN,Search Consultancy,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
773672,Data Analyst,Data Analyst III - Hybrid - Remote | WFH,Anywhere,via LinkedIn,Full-time,True,"New York, United States",2023-10-06 00:59:57,False,False,United States,None,NaN,NaN,Get It Recruit - Finance,"['sql', 'excel', 'tableau', 'power bi']","{'analyst_tools': ['excel', 'tableau', 'power ..."
175048,Data Analyst,Data QA Associate,"Buenos Aires, Argentina","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-08-01 15:18:41,False,False,Argentina,None,NaN,NaN,Fusemachines,"['sql', 'python', 'r', 'looker', 'git', 'jira']","{'analyst_tools': ['looker'], 'async': ['jira'..."

Let's inspect our index.

In [3]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
df.index.dtype

dtype('int64')

Our index is a range of numbers, inspecting the name...

In [5]:
df.index.name

It has no name... so let's name it.

In [6]:
df.index.name = 'job_index'

Inspecting it.

In [7]:
df.index.name

'job_index'

In [8]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
53153,Data Scientist,Data Science Lead,"San Francisco, CA",via BeBee,Full-time,False,"California, United States",2023-09-17 06:03:05,False,False,United States,None,NaN,NaN,Source Technology,['r'],{'programming': ['r']}
45641,Data Engineer,Interim Data Engineer,"Rotterdam, Netherlands",via Indeed,Full-time,False,Netherlands,2023-01-03 15:47:55,True,False,Netherlands,None,NaN,NaN,it-contracts,"['python', 'r', 'azure', 'databricks', 'airflo...","{'cloud': ['azure', 'databricks'], 'libraries'..."
93355,Software Engineer,Block Chain Senior Backend Engineer,Singapore,via Recruit.net,Full-time,False,Singapore,2023-07-09 00:13:30,False,False,Singapore,None,NaN,NaN,Kaya Tech Pte. Ltd.,"['java', 'python', 'aws', 'azure', 'kafka', 's...","{'cloud': ['aws', 'azure'], 'libraries': ['kaf..."

### Example 2

 Remember the pivot table we made in the last example? Where we got median yearly salaries for the different job titles. Let's run that code. Then we'll get the index name and the data type of the index using `df.index.name` and `df.index.dtype`.

In [9]:
median_pivot = df.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc='median')
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [11]:
index_name = median_pivot.index.name  
index_name

'job_title_short'

In [12]:
index_dtype = median_pivot.index.dtype  
index_dtype

dtype('O')

## reset_index()

### Notes 

* `reset_index()`: Resets the DataFrame’s index to the default integer index. This is particularly useful after operations that alter the index, like sorting or filtering, to simplify further data manipulation.

### Example 1

When we create new DataFrames by filtering this jacks up our index!

In [13]:
df_usa = df[df['job_country'] == 'United States']

df_usa.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [16]:
df_usa.index

RangeIndex(start=0, stop=206292, step=1)

Index is no longer correctly spaced by 1 increment.

In [15]:
df_usa.reset_index(inplace=True)
df_usa.head()

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

Technically we could `.drop()` the `job_index`.

BUT, if we wanted to do some sort of merge operations in the future with our original DataFrame, this provides the unique `id` to do that.

### Example 2

Back to our main DataFrame with our job postings in it. We're going to actually reset the indexes in the pivot table so `job_title_short` isn't the index anymore.

In [27]:
median_pivot.reset_index(inplace=True)
median_pivot

             job_title_short  index  salary_year_avg
0           Business Analyst      0          85000.0
1             Cloud Engineer      1          90000.0
2               Data Analyst      2          90000.0
3              Data Engineer      3         125000.0
4             Data Scientist      4         127500.0
5  Machine Learning Engineer      5         106415.0
6        Senior Data Analyst      6         111175.0
7       Senior Data Engineer      7         147500.0
8      Senior Data Scientist      8         155500.0
9          Software Engineer      9          99150.0

## set_index()

### Notes

* `set_index()`: Sets one or more existing columns as the index of the DataFrame. This is useful for timeseries data or when you want to index by specific attributes.

### Example 1

What if we wanted to go back to job_index as our main index?

In [20]:
df_usa.set_index('job_index', inplace=True)

df_usa.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

### Example 2

Now that we've reset our index we can set the new index on another column like `salary_year_avg`.

In [28]:
median_pivot.set_index('job_title_short', inplace=True)
median_pivot

                           index  salary_year_avg
job_title_short
Business Analyst               0          85000.0
Cloud Engineer                 1          90000.0
Data Analyst                   2          90000.0
Data Engineer                  3         125000.0
Data Scientist                 4         127500.0
Machine Learning Engineer      5         106415.0
Senior Data Analyst            6         111175.0
Senior Data Engineer           7         147500.0
Senior Data Scientist          8         155500.0
Software Engineer              9          99150.0

## sort_index()

### Notes 

* `sort_index()`: Sorts the DataFrame by the index (row labels), either ascending or descending. This helps in quickly organizing data by the index and is often used after `set_index()`.

### Example

Back to our pivoted DataFrame let's sort this new index alphabetically.

In [29]:
median_pivot.sort_index(inplace=True)
median_pivot

                           index  salary_year_avg
job_title_short
Business Analyst               0          85000.0
Cloud Engineer                 1          90000.0
Data Analyst                   2          90000.0
Data Engineer                  3         125000.0
Data Scientist                 4         127500.0
Machine Learning Engineer      5         106415.0
Senior Data Analyst            6         111175.0
Senior Data Engineer           7         147500.0
Senior Data Scientist          8         155500.0
Software Engineer              9          99150.0